# 芯片/实验参数
NUM_VECTORS = 11
VOLTAGE_RANGE = (0.0, 2.0)
TARGET_SPECTRUM_FILE = 'data/fsr1.xlsx'

# 优化器参数
OPTIMIZER_CALLS = 150
OPTIMIZER_RANDOM_STARTS = 20

# OSA扫描参数
OSA_WAVELENGTH_START = 1550.0
OSA_WAVELENGTH_STOP = 1551.0
OSA_RESOLUTION = 1.0 / 1400

# 模拟模式开关: True表示不连接真实硬件，方便调试
MOCK_HARDWARE = True

# 硬件连接地址 (在真实模式下使用)
OSA_ADDRESS = 'GPIB0::1::INSTR'
VOLTAGE_SOURCE_ADDRESS = 'ASRL4::INSTR'